name: thatch_mobile_application
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  sizer: ^2.0.15
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  toggle_switch: ^2.1.0
  flutter: 
    sdk: flutter
  dropdown_button2: ^2.3.7

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/png/
    - assets/images/svg/
  fonts: 
    - family: Candara
      fonts: 
        - asset: fonts/Candara-Font.ttf
  uses-material-design: true

